jwt:
  algorithm: "RS256"
  issuer: "notepot_auth-service"
  audience: "notepot-services"
  access_token_ttl_minutes: 15
  refresh_token_ttl_days: 30
  key_rotation_days: 90
  key_size: 2048
account:
  password:
    bcrypt_rounds: 12
    min_length: 8
    max_length: 128
  username:
    min_length: 3
    max_length: 50
    reserved_words:
      - "admin"
      - "root"
      - "api"
      - "system"
      - "user"
  email:
    max_length: 255
login:
  rate_limits:
    enabled: False # TODO: Enable rate limiting
    per_ip_requests: 20
    per_ip_window_minutes: 15
    per_identifier_attempts: 5
    per_identifier_window_minutes: 15
    per_account_attempts: 10
    per_account_window_minutes: 60
  security:
    enable_account_lockout: True
    lockout_duration_minutes: 60
    enable_audit_logging: True
  session:
    max_sessions_per_user: 10
redis:
  url: "redis://localhost:6379/0"
