# Database Configuration for Notepot

development:
  database:
    host: localhost
    port: 26257
    user: notepot_dev
    password: dev_password
    dbname: notepot_dev
    sslmode: disable
    max_idle_conns: 10
    max_open_conns: 100
    conn_max_lifetime: 3600s

test:
  database:
    host: localhost
    port: 26257
    user: notepot_test
    password: test_password
    dbname: notepot_test
    sslmode: disable
    max_idle_conns: 5
    max_open_conns: 25
    conn_max_lifetime: 1800s

production:
  database:
    host: ${DB_HOST}
    port: ${DB_PORT}
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    dbname: ${DB_NAME}
    sslmode: require
    max_idle_conns: 20
    max_open_conns: 200
    conn_max_lifetime: 3600s
